name: Deploy to Replit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via Replit webhook
      run: |
        curl -X POST "https://replit.com/data/web_repl_webhook/NutritiousAncientCubase" \
        -H "Content-Type: application/json" \
        -d '{"secret":"YOUR_SECRET","command":"git pull && python3 main.py"}'
