name: Daily Weather Bot

on:
  schedule:
    # Chạy lúc 7:00 AM UTC+7 (0:00 AM UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  send-weather:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run weather bot
      run: python main.py
      env:
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        
    - name: Log completion
      run: echo "Weather bot completed at $(date)"
